name = "onedrive-index"
type = "webpack"
workers_dev = true
account_id = "4d206d1f651506260d28c7456b58169b"
zone_id = "29aa3530fa4d8a89dacf8af26cea6a99"
kv_namespaces = [
    { binding = "BUCKET", preview_id = "60cdebe4576a4616bee8015947c56112", id = "893b48690fbc4dc3b7fa0931d74f09bf" }
]

[env.staging]
name = "drive-staging"
